volumes:
  postgres:
services:
  postgres:
    environment:
    - POSTGRES_DB=keycloak
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=password
    image: postgres:16
    volumes:
    - postgres:/var/lib/postgresql
  openldap:
    image: bitnami/openldap:2.6
    environment:
      LDAP_PORT_NUMBER: 389
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    command: --verbose start-dev --features=preview
    depends_on:
    - postgres
    - openldap
    environment:
    - KEYCLOAK_ADMIN=keycloak
    - KEYCLOAK_ADMIN_PASSWORD=password
    - KC_LOG_LEVEL=INFO
    - KC_DB=postgres
    - KC_DB_URL_HOST=postgres
    - KC_DB_URL_PORT=5432
    - KC_DB_URL_DATABASE=keycloak
    - KC_DB_USERNAME=keycloak
    - KC_DB_PASSWORD=password
# Enable for remote java debugging
#    - PREPEND_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8787
    ports:
    - 8080:8080
# Enable for remote java debugging
#    - 8787:8787
    volumes:
# Make the custom-user-federation-example extension available to Keycloak. The :z option is required and tells Docker that the volume content will be shared between containers.
    - ./custom-user-federation-example/build/libs/custom-user-federation-example-all.jar:/opt/keycloak/providers/custom-user-federation-example-all.jar:z
    - ./provider/misc:/opt/keycloak/misc:z
